spring:
  application:
    name: keyguard
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:h2:mem:keyguard;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

server:
  port: ${PORT:8080}

keyguard:
  prefix: ${KEYGUARD_PREFIX:nslsk}
  protected-path-prefix: /api/v1/todolist
  forwarded-for-header: X-Forwarded-For
  api-key-header: X-API-KEY