create table if not exists api_keys (
    id bigint generated by default as identity primary key,
    vendor_name nvarchar(100) not null,
    key_hash char(64) not null,
    allow_ip nvarchar(500),
    status varchar(10) not null,
    created_user nvarchar(20) not null,
    created_at timestamp not null,
    updated_user nvarchar(20),
    updated_at timestamp
);

create unique index if not exists uk_api_keys_key_hash on api_keys(key_hash);